# Where are all the schema files located? globs are supported eg  src/**/*.graphqls
schema:
  - "*.graphqls"

# Where should the generated server code go?
exec:
  filename: generated.go
  package: graph

# Where should any generated models go?
model:
  filename: model/models_gen.go
  package: model

# Where should the resolver implementations go?
resolver:
  layout: follow-schema
  dir: .
  package: graph
